[package]
name = "beetle"
version = "0.0.1"
authors = ["not_a_seagull <jtnunley01@gmail.com>"]
edition = "2018"

[dependencies]
lazy_static = "1"
nalgebra = "0.21"
owning_ref = "0.4"
thiserror = "1"

[target.'cfg(windows)'.dependencies]
winapi = { version = "0.3", features = ["std", "winuser", "windef", "minwindef", "errhandlingapi"] }

[target.'cfg(target_os = "macos")'.dependencies]
objc = "0.2"
block = "0.1"

[target.'cfg(target_os = "linux")'.dependencies]
freetype = "0.5"
x11 = "2"

[profile.release]
lto = true
