[package]
name = "beetle-useful-macros"
version = "0.1.0"
authors = ["not_a_seagull <jtnunley01@gmail.com>"]
edition = "2018"

[lib]
proc-macro = true

[dependencies]
proc-macro2 = "*"
syn = "1"
quote = "1"
